version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONFIG_NAME: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:password@pg/postgres
    ports:
      - "5080:80"
    depends_on:
      - pg

  pg:
    image: postgres
    env_file:
      - postgres.env
    ports:
      - 5432:5432
#    volumes:
#      - pg-data:/var/lib/postgresql/data/

#volumes:
#  pg-data:


